config/routes.rb
Kent::Application.routes.draw do
  
  devise_for :users

  resources :comics do
    resources :chapters do
      resources :pages
    end
  end

  root to: 'comics#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :manage, Comic, user_id: user.id
      can :manage, Chapter if can? :manage, Comic
      can :manage, Page if can? :manage, Chapter
    end
    can :read, :all
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :comic
  has_many :pages, order: 'number ASC, id ASC'

  attr_accessor :file

  scope :available, where(locked: false)
end

app/models/comic.rb
class Comic < ActiveRecord::Base
  
  belongs_to :user
  has_many :chapters,  order: 'issue ASC, id ASC'

  mount_uploader :thumbnail, ThumbnailUploader

  validates_presence_of :title, :description
end

app/models/comic_observer.rb
class ComicObserver < ActiveRecord::Observer
	
  def before_save(comic)
  	true
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :chapter, dependent: :destroy
  mount_uploader :image, PageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    chapter = Chapter.new chapter_params
    if chapter.save
      flash[:notice] = 'The chapter is being processed. Please wait a couple of minutes.'
      ProcessPagesJob.new.async.perform(current_user, chapter)
    else
      flash[:alert] = 'Chapter not processable'
    end
    redirect_to comic_path(params[:comic_id])
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :issue, :file)
    end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_filter :set_comic, except: [:index, :new, :create] 
  authorize_resource except: [:index, :show]

  # GET /comics
  # GET /comics.json
  def index
    @comics = Comic.all
  end

  def new
    @comic = current_user.comics.build
  end

  # POST /comics
  # POST /comics.json
  def create
    @comic = current_user.comics.build(comic_params)
    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comic }
      else
        format.html { render action: 'new' }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comics/1
  # PATCH/PUT /comics/1.json
  def update
    respond_to do |format|
      debugger
      if @comic.update(comic_params)
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic
      @comic = Comic.find(params[:id]) 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comic_params
      params.require(:comic).permit(:title, :genre, :state, :description, :thumbnail)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @page }
      else
        format.html { render action: 'new' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:image, :number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chapters/_form.html.haml
= simple_form_for @chapter, url: comic_chapters_path(comic_id: params[:comic_id]) do |f|
  - if @chapter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chapter.errors.count, "error")} prohibited this chapter from being saved:"
      %ul
        - @chapter.errors.full_messages.each do |msg|
          %li= msg

  = f.input :file, as: :file, required: true
  = f.input :title
  = f.input :issue
  .actions
    = f.submit 'Save'

app/views/chapters/edit.html.haml
%h1 Editing chapter

= render 'form'

= link_to 'Show', @chapter
\|
= link_to 'Back', chapters_path

app/views/chapters/index.html.haml
%h1 Listing chapters

%table
  %tr
    %th Cover
    %th Title
    %th Issue
    %th
    %th
    %th

  - @chapters.each do |chapter|
    %tr
      %td= chapter.cover
      %td= chapter.title
      %td= chapter.issue
      %td= link_to 'Show', chapter
      %td= link_to 'Edit', edit_chapter_path(chapter)
      %td= link_to 'Destroy', chapter, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Chapter', new_comic_chapter_path

app/views/chapters/new.html.haml
%h1 New chapter

= render 'form'

= link_to 'Back', comic_chapters_path

app/views/chapters/show.html.haml
.row
  .large-12.columns
    %h1
    %b Title:
    = @chapter.title
    #flipbook
      - @chapter.pages.find_each do |page|
        %div{dir: "rtl"}= image_tag(page.image, class: 'chapter-page')
.row
  .small-12.columns
    %p
      %b Issue:
      = @chapter.issue

    = link_to 'Edit', edit_comic_chapter_path(id: @chapter, comic_id: @chapter.comic_id)

app/views/comics/_comic.html.haml
%li.comic-thumbnail
  = link_to(image_tag(comic.thumbnail.thumb.url || '/assets/placeholder-thumbnail.png'), comic)
  %p= comic.title

app/views/comics/_form.html.haml
= simple_form_for(@comic) do |f|
  - if @comic.errors.any?
    #error_explanation
      %h2
        = pluralize(@comic.errors.count, "error")
        prohibited this comic from being saved:
      %ul
        - @comic.errors.full_messages.each do |msg|
          %li= msg

  .row
    .medium-4.columns= image_tag( @comic.thumbnail.present? ? @comic.thumbnail : '/assets/placeholder.jpg')
    .medium-8.columns
      = f.input :title
      = f.input :genre
      = f.input :author
      = f.input :state, collection: [:open, :closed, :hiatus, :ongoing], include_blank: false
      = f.input :thumbnail, as: :file

      = f.input :description
      = f.submit class: 'button small'

app/views/comics/_most_popular.html.haml
%tr
  %td.title= link_to comic.title, comic_path(comic.id)
  %td.author= comic.author
  %td.chapters= comic.chapters.count
  %td.scode= 8.5

app/views/comics/edit.html.haml
%h1 Editing comic
= render 'form'
= link_to 'Show', @comic
|
\#{link_to 'Back', comics_path}

app/views/comics/index.html.haml
%h1 Listing comics

.row
  .large-5.columns.secondary-nav 
    %table.responsive
      %thead
        %tr
          %th Title
          %th Author
          %th Chapters
          %th Score
      %tbody
      = render partial: 'most_popular', collection: @comics, as: 'comic'

  .large-7.columns
    %ul.clearing-thumbs.small-block-grid-3= render partial: 'comic', collection: @comics

= link_to 'New Comic', new_comic_path

app/views/comics/new.html.haml
%h1 New comic
= render 'form'
= link_to 'Back', comics_path

app/views/comics/show.html.haml
.row
  .large-8.columns
    = image_tag( @comic.thumbnail.present? ? @comic.thumbnail : '/assets/placeholder.jpg')
  
  .large-4.columns
    %p 
      %strong Title:
      = @comic.title
    %p 
      %strong Genre:
      = @comic.genre
    %p 
      %strong State:
      = @comic.state
    %p 
      %strong Description:
      = @comic.description
    = link_to 'Edit', edit_comic_path(@comic)
    |
    \#{link_to 'Back', comics_path}

    %hr
    %p= link_to 'Upload chapters', new_comic_chapter_path(@comic), class: 'button'
.row
  .small-12
    - @comic.chapters.each do |chapter|
      = link_to chapter.issue, comic_chapter_path(comic_id: @comic.id, id: chapter)

app/views/layouts/_navigation.html.haml
#nav-bar
  .row
    %nav.top-bar{"data-topbar" => ""}
      %ul.title-area
        %li.name
          %h1= link_to('Kent', root_path, class: 'app-logo')
        -  if current_user
          %li.toggle-topbar.menu-icon
            %a{href: "#"}
      -  if current_user
        %section.top-bar-section
          / Right Nav Section
          %ul.right          
            %li.has-dropdown
              = link_to( "Hi, User", '#')
              %ul.dropdown
                %li= link_to("Profile", edit_user_registration_path)
                %li= link_to("Logout", destroy_user_session_path, :method => :delete) 
            %li.has-dropdown
              = link_to 'Actions', '#'
              %ul.dropdown
                %li= link_to 'My comics'
                %li= link_to 'Create new Comic', new_comic_path
                - if params[:action] == 'show' && params[:controller] == 'comics'
                  %li= link_to 'Upload chapters', new_comic_chapter_path(@comic)

      -  else
        %section.top-bar-section
          / Right Nav Section
          %ul.right          
            %li= link_to 'Sign in', new_user_session_path
            %li= link_to 'Sign up', new_user_registration_path 

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "foundation-rails"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    .row
      .large-12.columns= yield
    = javascript_include_tag "application"

app/views/pages/_form.html.haml
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :number
    = f.text_field :number
  .actions
    = f.submit 'Save'

app/views/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', @page
\|
= link_to 'Back', pages_path

app/views/pages/index.html.haml
%h1 Listing pages

%table
  %tr
    %th Image
    %th Number
    %th
    %th
    %th

  - @pages.each do |page|
    %tr
      %td= page.image
      %td= page.number
      %td= link_to 'Show', page
      %td= link_to 'Edit', edit_page_path(page)
      %td= link_to 'Destroy', page, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Page', new_page_path

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.haml
%p#notice= notice

%p
  %b Image:
  = @page.image
%p
  %b Number:
  = @page.number

= link_to 'Edit', edit_page_path(@page)
\|
= link_to 'Back', pages_path